#%RAML 1.0
title: ACME Banking API
version: 1.0
baseUri: http://www.placeholder.com/api/{version}/

documentation:
  - title: ACME Banking API
    content: |
      This is the partial API for instructors to use as a sample solution for the API Design and Architecture class.

mediaType: application/json

/customers:
  description: "The full collection of all users with accounts at the bank"
  get:
    description: "[FR-005] Retrieve a full list of customers"
    responses:
      200:
        body:
          example: |
            [
              {
                "user_id": "1234",
                "user_name": "Nora Charles",
                "description": "This is the ACME account of Nora Charles",
                "dob": "01/01/1970"
              },
              {
                "user_id": "4321",
                "user_name": "Ray Charles",
                "description": "This is the ACME account of Ray Charles",
                "dob": "01/01/1970"
              }
            ]
      404:
        body:
          example: |
            {
              "http.statuscode" : 404,
              "message" : "Resource not found."
            }
  post:
    description: "[FR-010] Add a new customer"
    body:
      example: |
        {
          "user_name": "John Doe",
          "description": "This is the ACME account of John Doe",
          "dob": "01/01/1970"
        }
    responses:
      201:
        body:
          example: |
            {
              "http.statuscode" : 201,
              "message" : "Resource created."
            }
  /{customer_id}:
    uriParameters:
      customer_id:
        displayName: Customer ID
        type: string
    get:
      description: "[FR-015] Retrieve details on a particular customer"
      responses:
        200:
          body:
            example: |
              {
                "user_id": "4321",
                "user_name": "Ray Charles",
                "description": "This is the ACME account of Ray Charles",
                "dob": "01/01/1970"
              }
        404:
          body:
            example: |
              {
                "http.statuscode" : 404,
                "message" : "Resource not found."
              }
    delete:
      description: Delete a specific customer
      responses:
        200:
          body:
            example: |
              {
                "http.statuscode" : 200,
                "message" : "Operation completed successfully."
              }
    put:
      description: "[FR-002] Update or create a specific customer"
      body:
        example: |
          {
            "user_id": "9999",
            "user_name": "John Doe",
            "description": "This is the ACME account of John Doe",
            "dob": "01/01/1970"
          }
      responses:
        200:
          body:
            example: |
              {
                "http.statuscode" : 200,
                "message" : "Operation completed successfully."
              }
        201:
          body:
            example: |
              {
                "http.statuscode" : 201,
                "message" : "Resource created."
              }
    /accounts:
      get:
        description: "[FR-012] Get a list of accounts belonging to a particular customer"
        responses:
          200:
            body:
              example: |
                [
                  {
                    "account_id" : "a2esd212343123",
                    "account_type" : "checking",
                    "customer_id" : "1234",
                    "balance": 1252.00
                  },
                  {
                    "account_id" : "a3esd212343123",
                    "account_type" : "savings",
                    "customer_id" : "4321",
                    "balance": 13000.00
                  }
                ]
      post:
        description: "[FR-006] Add an account to a customer"
        body:
          example: |
            {
              "account_type" : "checking",
              "customer_id" : "9999",
              "balance": 0.00
            }
        responses:
          201:
            body:
              example: |
                {
                  "http.statuscode" : 201,
                  "message" : "Resource created."
                }
      /{account_id}:
        uriParameters:
          account_id:
            type: integer
        get:
          description: "[FR-011] Retrieve a detailed account report"
          responses:
            200:
              body:
                example: |
                  {
                    "account_id" : "a3esd212343123",
                    "account_type" : "checking",
                    "customer_id" : "1234",
                    "balance": 113300.00
                  }
            404:
              body:
                example: |
                  {
                    "http.statuscode" : 404,
                    "message" : "Resource not found."
                  }
        put:
          description: "[FR-001] Update bank account information"
          responses:
            200:
              body:
                example: |
                  {
                    "http.statuscode" : 200,
                    "message" : "Operation completed successfully."
                  }
            201:
              body:
                example: |
                  {
                    "http.statuscode" : 201,
                    "message" : "Resource created."
                  }
        delete:
          description: "[FR-007] Remove an account from a customer"
          responses:
            200:
              body:
                example: |
                  {
                    "http.statuscode" : 200,
                    "message" : "Operation completed successfully."
                  }
        /outgoingTransfers:
          get:
            description: "[FR-008] Retrieve a list of a customer’s outgoing transfers"
            responses:
              200:
                body:
                  example: |
                    [
                      {
                        "sourceAccount_id" : "3523djfg329548",
                        "targetAccount_id" : "a2esd212343123",
                        "amount": 27.00,
                        "description": "My share of last night's dinner"
                      },
                      {
                        "sourceAccount_id" : "3523djfg123123",
                        "targetAccount_id" : "a2esd212343123",
                        "ammount": 1324.00,
                        "description": "rent June 2015"
                      }
                    ]
          post:
            description: "[FR-009] Create an outgoing transfer from a customer’s account to another account"
            responses:
              201:
                body:
                  example: |
                    {
                      "http.statuscode" : 201,
                      "message" : "Resource created."
                    }
          /{transfer_id}:
            get:
              description: "[FR-014] Retrieve details on a particular outgoing transfer"
              responses:
                200:
                  body:
                    example: |
                      {
                        "sourceAccount_id" : "a2esd212343123",
                        "targetAccount_id" : "3523djfg329548",
                        "amount": 1000.00,
                        "description": "This is the description of a particular transaction that you provided at creation."
                      }
                404:
                  body:
                    example: |
                      {
                        "http.statuscode" : 404,
                        "message" : "Resource not found."
                      }
        /incomingTransfers:
          get:
            description: "[FR-013] Retrieve a list of incoming transfers for a particular bank account"
            responses:
              200:
                body:
                  example: |
                    [
                      {
                        "sourceAccount_id" : "3523djfg329548",
                        "targetAccount_id" : "a2esd212343123",
                        "amount": 27.00,
                        "description": "My share of last night's dinner"
                      },
                      {
                        "sourceAccount_id" : "3523djfg123123",
                        "targetAccount_id" : "a2esd212343123",
                        "ammount": 1324.00,
                        "description": "rent June 2015"
                      }
                    ]
          /{transfer_id}:
            get:
              description: "[FR-003] Retrieve details on a particular incoming transfer"
              responses:
                200:
                  body:
                    example: |
                      {
                        "sourceAccount_id" : "a2esd212343123",
                        "targetAccount_id" : "3523djfg329548",
                        "amount": 1000.00,
                        "description": "This is the description of a particular transaction that you provided at creation."
                      }
                404:
                  body:
                    example: |
                      {
                        "http.statuscode" : 404,
                        "message" : "Resource not found."
                      }
/transfers:
 get:
   description: "[FR-004] Retrieve a list of all transfers, both incoming and outgoing."
   responses:
     200:
       body:
         example: |
           [
             {
               "sourceAccount_id" : "3523djfg329548",
               "targetAccount_id" : "a2esd212343123",
               "amount": 27.00,
               "description": "My share of last night's dinner"
             },
             {
               "sourceAccount_id" : "3523djfg123123",
               "targetAccount_id" : "a2esd212343123",
               "ammount": 1324.00,
               "description": "rent June 2015"
             }
           ]
